USER_AUTH_TABLE = "OuraUserAuth"
USER_INFO_TABLE_SUFFIX = "OuraUserInfo"
READINESS_TABLE_SUFFIX = "OuraReadiness"
SLEEP_TABLE_SUFFIX = "OuraSleep"
ACTIVITY_TABLE_SUFFIX = "OuraActivity"
BEDTIME_TABLE_SUFFIX = "OuraBedtime"

OURA_SECRET_SUFFIX = "oura"
