openapi: 3.0.0
components:
  schemas:
    ApiResponse:
      title: ApiResponse
      type: object
      properties:
        message:
          title: Message
          type: string
      required:
        - message
    ApiError:
      title: ApiError
      type: object
      properties:
        error:
          title: Error
          type: string
      required:
        - error
    IntegerTimeSeries:
      title: IntegerTimeSeries
      type: object
      properties:
        start_epoch_seconds:
          title: Start Epoch Seconds
          type: integer
        end_epoch_seconds:
          title: End Epoch Seconds
          type: integer
        mean:
          title: Mean
          type: number
        standard_deviation:
          title: Standard Deviation
          type: number
        sample_count:
          title: Sample Count
          type: integer
        max:
          title: Max
          type: integer
        median:
          title: Median
          type: integer
        min:
          title: Min
          type: integer
      required:
        - start_epoch_seconds
        - end_epoch_seconds
    IntegerTimeSeriesBatch:
      title: IntegerTimeSeriesBatch
      type: object
      properties:
        batch:
          title: Batch
          type: array
          items:
            $ref: '#/components/schemas/IntegerTimeSeries'
      required:
        - batch
  securitySchemes:
    congitoUserPool:
      type: oauth2
      description: Cognito user pool auth code with PKCE
      flows:
        authorizationCode:
          authorizationUrl: >-
            https://hearty-dev-admin.auth.us-east-1.amazoncognito.com/oauth2/authorize
          tokenUrl: >-
            https://hearty-dev-admin.auth.us-east-1.amazoncognito.com/oauth2/token
          refreshUrl: >-
            https://hearty-dev-admin.auth.us-east-1.amazoncognito.com/oauth2/token
          scopes:
            email: Access email address
            profile: Access profile details
info:
  title: Hearty Admin API
  description: Internal API to support admin user operations
  version: 0.0.1
paths:
  '/client/healthkit/heart-rates/{userId}':
    get:
      operationId: healthkit-get-heartrates
      summary: Retrieve a batch of heart rate time series data
      description: >-
        Returns a batch a user's heart rate time series data. Data is keyed by
        the user_id
      tags:
        - healthkit
      parameters:
        - name: userId
          in: path
          description: The user ID of the patient for which to retrieve heart rates
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status 200 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntegerTimeSeriesBatch'
        '400':
          description: Status 400 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Status 500 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
security:
  - congitoUserPool:
      - email
      - profile
