service: ${self:custom.common.service}-client
configValidationMode: ${self:custom.common.configValidationMode}

plugins: ${self:custom.common.plugins}

custom:
  common: ${file(serverless.common.yml)}
  pythonRequirements: ${self:custom.common.pythonRequirements}
  prune: ${self:custom.common.prune}
  infra: ${self:custom.common.infra.${opt:stage}}
  doc_directory: "doc/api/client"
  documentation: ${file(${self:custom.doc_directory}/documentation.yml):documentation}

package: ${self:custom.common.package}

provider:
  name: ${self:custom.common.provider.name}
  runtime: ${self:custom.common.provider.runtime}
  memorySize: ${self:custom.common.provider.memorySize}
  region: ${self:custom.common.provider.region}
  timeout: ${self:custom.common.provider.timeout}
  stackPolicy: ${self:custom.common.provider.stackPolicy}
  httpApi:
    authorizers:
      heartyUserPoolAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ''
            - - 'https://cognito-idp.'
              - '${opt:region, self:provider.region}'
              - '.amazonaws.com/'
              - Ref: heartyUserPool
        audience:
          - Ref: heartyUserPoolClient
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:BatchWriteItem
          Resource: arn:aws:dynamodb:${self:custom.common.provider.region}:*:table/${self:custom.common.custom.appEnv}*

resources:
  Resources:
    HttpApi:
      DependsOn: heartyUserPool
    ## Patient User Cognito Objects ##
    heartyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        AutoVerifiedAttributes:
          - email
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: true
          DeviceOnlyRememberedOnUserPrompt: false
        EnabledMfas:
          - SOFTWARE_TOKEN_MFA
        MfaConfiguration: OPTIONAL
        Policies:
          PasswordPolicy:
            MinimumLength: 10
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        UsernameAttributes:
          - email
        UsernameConfiguration:
          CaseSensitive: true
        UserPoolAddOns:
          AdvancedSecurityMode: ENFORCED
        UserPoolName: ${self:custom.common.custom.appEnv}-user-pool
    heartyUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.common.custom.appEnv}-user-app
        AllowedOAuthFlows:
          - code
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - phone
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        UserPoolId:
          Ref: heartyUserPool
        CallbackURLs:
          - https://localhost:3000
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
        SupportedIdentityProviders:
          - COGNITO
    heartyeUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId:
          Ref: heartyUserPool
        Domain: ${self:custom.common.custom.appEnv}

functions:
  echo:
    handler: hearty.api.lambdas.echo.echo
    events:
      - httpApi:
          authorizer: heartyUserPoolAuthorizer
          path: /echo
          method: post
  oura-authorize-user:
    handler: hearty.api.client.lambdas.oura.authorize_user
    events:
      - httpApi:
          authorizer: heartyUserPoolAuthorizer
          path: /client/oura/authorize-user
          method: post
          documentation: ${file(${self:custom.doc_directory}/endpoints.yml):oura-authorize-user}
  healthkit-save-heartrates:
    handler: hearty.api.client.lambdas.healthkit.save_heart_rates
    events:
      - httpApi:
          authorizer: heartyUserPoolAuthorizer
          path: /client/healthkit/heart-rates
          method: post
          documentation: ${file(${self:custom.doc_directory}/endpoints.yml):healthkit-save-heartrates}
