service: ${self:custom.common.service}
configValidationMode: ${self:custom.common.configValidationMode}

plugins: ${self:custom.common.plugins}

custom:
  common: ${file(serverless.common.yml)}
  pythonRequirements: ${self:custom.common.pythonRequirements}
  prune: ${self:custom.common.prune}

package: ${self:custom.common.package}

provider:
  name: ${self:custom.common.provider.name}
  runtime: ${self:custom.common.provider.runtime}
  memorySize: ${self:custom.common.provider.memorySize}
  region: ${self:custom.common.provider.region}
  environment:
    DOMAIN_SUFFIX: hearty-${opt:stage, self:provider.stage}
  httpApi:
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ''
            - - 'https://cognito-idp.'
              - '${opt:region, self:provider.region}'
              - '.amazonaws.com/'
              - Ref: serviceUserPool
        audience:
          - Ref: serviceUserPoolClient
  stackPolicy:
    - Effect: Allow
      Principal: '*'
      Action: 'Update:*'
      Resource: '*'
    - Effect: Deny
      Principal: '*'
      Resource: '*'
      Action:
        - Update:Replace
        - Update:Delete
      Condition:
        StringEquals:
          ResourceType:
            - AWS::DynamoDB::Table
            - AWS::Cognito::UserPool
            - AWS::Cognito::UserPoolClient
            - AWS::Cognito::UserPoolDomain

resources:
  Resources:
    HttpApi:
      DependsOn: serviceUserPool
    serviceUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: service-user-pool-${opt:stage, self:provider.stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    serviceUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: service-user-pool-client-${opt:stage, self:provider.stage}
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - phone
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        UserPoolId:
          Ref: serviceUserPool
        CallbackURLs:
          - https://localhost:3000
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
        SupportedIdentityProviders:
          - COGNITO
    serviceUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId:
          Ref: serviceUserPool
        Domain: service-user-pool-domain-${opt:stage, self:provider.stage}-${self:provider.environment.DOMAIN_SUFFIX}
    secretsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.common.custom.appEnv}-secrets
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: app_name
            AttributeType: S
        KeySchema:
          - AttributeName: app_name
            KeyType: HASH
    ouraUserAuthTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.common.custom.appEnv}-OuraUserAuth
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
    ouraUserInfoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.common.custom.appEnv}-OuraUserInfo
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
    ouraReadinessTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.common.custom.appEnv}-OuraReadiness
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: summary_date
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: summary_date
            KeyType: RANGE
    ouraSleepTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.common.custom.appEnv}-OuraSleep
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: summary_date
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: summary_date
            KeyType: RANGE
    ouraActivityTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.common.custom.appEnv}-OuraActivity
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: summary_date
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: summary_date
            KeyType: RANGE
    ouraBedtimeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.common.custom.appEnv}-OuraBedtime
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: summary_date
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: summary_date
            KeyType: RANGE

functions:
  echo:
    handler: hearty.lambdas.echo.echo
    events:
      - httpApi:
          authorizer: serviceAuthorizer
          path: /echo
          method: post
